export const TRAINER_CONFIG = {
  learnerLanguage: 'ru',
  emaAlpha: 0.15,
  familiarityDiscount: 0.75,
  familiarWordEvidenceFloor: 0.25,
  verificationFamiliarityThreshold: 0.4,
  alphabetLearningThreshold: 0.6,
  strongThreshold: 0.75,
  unverifiedScoreCeiling: 0.74,
  bootstrapFamiliarityThreshold: 0.8,
  bootstrapLoanwordThreshold: 0.8,
  recentWordWindow: 20,
  bootstrapSuccessfulWords: 40,
  bootstrapKnownLetters: 12,
  familiarInjectionInterval: 7,
  maxUnknownLettersIntroduction: 1,
  reinforcementWords: 3,
  targetSuccess: 0.78,
  spacingMs: 86_400_000,
  weights: {
    weak: 0.35,
    spacing: 0.25,
    difficulty: 0.2,
    reinforcement: 0.1,
    novelty: 0.1,
    recent: 0.8,
  },
  difficulty: {
    length: 0.1,
    visual: 0.1,
    reading: 0.15,
    familiarity: 0.3,
    frequency: 0.1,
    averageUnknown: 0.35,
    weakest: 0.3,
  },
};
